; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = fatfs
build_flags = -DUSE_TINYUSB
board_build.arduino.earlephilhower.usb_manufacturer = RF.Guru
board_build.arduino.earlephilhower.usb_product = SmartVFO
board_build.arduino.earlephilhower.usb_vid = 0x1209
board_build.arduino.earlephilhower.usb_pid = 0xFF41
board_build.filesystem_size = 0.5m
lib_deps =
    https://github.com/FortySevenEffects/arduino_midi_library.git
